# Generated by Django 6.0.1 on 2026-05-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('resnet34', 'ResNet34'), ('resnet50', 'ResNet50'), ('vgg19', 'VGG19')], max_length=20)),
                ('model_file', models.FileField(upload_to='models/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image_hash', models.CharField(db_index=True, max_length=64)),
                ('resnet34_result', models.CharField(max_length=20)),
                ('resnet50_result', models.CharField(max_length=20)),
                ('vgg19_result', models.CharField(max_length=20)),
                ('final_result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
